# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Architect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Cartography'

  # Pods for Architect
  target 'ArchitectTests' do
    pod 'Quick'
    pod 'Nimble'
  end

end
